### ISSUE TITLE
Infinite loading bug when selecting disk as path

### ISSUE THREAD

**Issue by henriksen-marcus** [Deadpikle/EasyBackup#11]
## Bug Description

Infinite loading bug when choosing a disk as backup location, and not choosing a subfolder.

## Bug Solution

If unsupported the user should be prompted. Check the given path depth.

## How to reproduce the bug

1. Choose something to back up
2. When selecting a backup location, select a disk drive such as an SSD or external hard drive, and do not choose a subfolder within
3. Click **Run Backup**

## Environment

Windows 10

**Comment by Deadpikle** [comment]
Thank you very much for the report! This wasn't broken in the legacy Windows-only version, but definitely was in the newer Avalonia version. Should be fixed now. Will upload a new version here soon.
